[1779] => Array
        (
     
            [159] => Array
                (
                    [bookings] => Array
                        (
                            [Active] => Array
                                (
                                    [1] => Array
                                        (
                                            [114037] => Array
                                                (
                                                    [site_id] => 758
                                                    [note] => 
                                                )

                                        )

                                )

                        )

                    [attendance] => Array
                        (
                            [758] => Active
                        )

                    [casual_requests] => Array
                        (
                            [0] => 0
                        ) 
                )
